[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/submit-timesheet"
  to = "/.netlify/functions/submit-timesheet"
  status = 200

[functions]
  node_bundler = "esbuild"
